rule pythonscript:
    script:
        "C:\Python_files\Snakemake_practice\Assignment\src\MA.py",
rule pythonscript:
    script:
        "C:\Python_files\Snakemake_practice\Assignment\src\Volcano.py",