rule MA_plot:
    script:
        "/mnt/c/Python_files/EMBL_Tranee_assignment/Assignment/src/MA.py"
rule Volcano_plot:
    script:
        "/mnt/c/Python_files/EMBL_Tranee_assignment/Assignment/src/Volcano.py"